import { Product } from './supabase'

// Temporary hardcoded products until Supabase is set up
export const products: Product[] = [
  // Ultra Bee Parts
  {
    id: '1',
    name: 'Ultra Bee Baja Headlight Kit',
    slug: 'ultra-bee-baja-headlight',
    description: 'High-performance LED headlight kit for Ultra Bee',
    price: 29900,
    compare_price: null,
    image: 'baja-headlight.jpeg',
    category: 'ultra-bee',
    in_stock: true,
    badge: 'new',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Surron Ultra Bee Sintered Brake Pads',
    slug: 'ultra-bee-brake-pads',
    description: 'High-performance sintered brake pads',
    price: 4500,
    compare_price: 5500,
    image: 'brake-pads.jpeg',
    category: 'ultra-bee',
    in_stock: true,
    badge: 'sale',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Surron Ultra Bee Shift Lock',
    slug: 'ultra-bee-shift-lock',
    description: 'Prevents accidental gear shifts',
    price: 8900,
    compare_price: null,
    image: 'ultra-bee-shift-lock.jpg',
    category: 'ultra-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Ultra Bee Front Windscreen',
    slug: 'ultra-bee-windscreen',
    description: 'Aerodynamic front windscreen',
    price: 7900,
    compare_price: null,
    image: 'windscreen.jpeg',
    category: 'ultra-bee',
    in_stock: true,
    badge: 'new',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Ultra Bee Rear Fender',
    slug: 'ultra-bee-rear-fender',
    description: 'Replacement rear fender',
    price: 6500,
    compare_price: null,
    image: 'rear-fender.jpeg',
    category: 'ultra-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Surron Ultra Bee Guts Seat Cover',
    slug: 'ultra-bee-seat-cover',
    description: 'Premium GUTS Racing seat cover',
    price: 8500,
    compare_price: null,
    image: 'ultra-bee-seat-cover.png',
    category: 'ultra-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
  // Light Bee Parts
  {
    id: '7',
    name: 'Light Bee Front Number Plate',
    slug: 'light-bee-front-plate',
    description: 'MX-style front number plate',
    price: 4900,
    compare_price: 6500,
    image: 'front-plate.jpeg',
    category: 'light-bee',
    in_stock: true,
    badge: 'sale',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Light Bee Motor Guard',
    slug: 'light-bee-motor-guard',
    description: 'CNC machined motor protection',
    price: 11900,
    compare_price: null,
    image: 'motor-guard.jpeg',
    category: 'light-bee',
    in_stock: true,
    badge: 'new',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Light Bee Passenger Peg Kit',
    slug: 'light-bee-passenger-peg',
    description: 'Passenger foot peg mounting kit',
    price: 8900,
    compare_price: null,
    image: 'passenger-peg.jpeg',
    category: 'light-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Surron Light Bee Shift Lock',
    slug: 'light-bee-shift-lock',
    description: 'Prevents accidental gear shifts',
    price: 7900,
    compare_price: null,
    image: 'light-bee-shift-lock.jpg',
    category: 'light-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Surron Light Bee Motor Cover',
    slug: 'light-bee-motor-cover',
    description: 'Protective motor cover',
    price: 11900,
    compare_price: null,
    image: 'light-bee-motor-cover.webp',
    category: 'light-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Surron Light Bee Guts Seat Cover',
    slug: 'light-bee-seat-cover',
    description: 'Premium GUTS Racing seat cover',
    price: 8000,
    compare_price: null,
    image: 'light-bee-seat-cover.png',
    category: 'light-bee',
    in_stock: true,
    badge: null,
    created_at: new Date().toISOString(),
  },
]

export function getProductsByCategory(category: 'ultra-bee' | 'light-bee') {
  return products.filter(p => p.category === category)
}

export function getProductById(id: string) {
  return products.find(p => p.id === id)
}
